import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Tracking Signals',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'tracking-signals' }],
    },
    {
      type: 'category',
      label: 'Profit Strategy',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'profit-strategy' }],
    },
    {
      type: 'category',
      label: 'Agency Partners',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'agency-partners' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'troubleshooting' }],
    },
    'community-support',
  ],
};

export default sidebars;
